### PR TITLE
You have a dilemma

### PR DESCRIPTION
**Pull request by KyleSmith0905**
### Think hard about this pull request…
If you accept this pull request for your README.md, the URL to PeasAPI will no longer be broken; however, with the cost of a small typo I added. **Think hard about it… Your decision matters…**

### CODE REVIEW

**Comment by KyleSmith0905** [comment]
>This your last chance. After this there is no turning back. You take the blue pill, the story ends. You wake up in your bed and believe whatever you want to. You take the red pill, you stay in Wonderland, and I show you how deep the rabbit hole goes. Remember, all I'm offering is the truth. Nothing more.

*-The Matrix (Morpheus)*

**Comment by Peasplayer** [comment]
How about this: I delete your pr and fix the typo and no one will ever know about my dark side.

**Comment by KyleSmith0905** [comment]
# New offer

## Introduction
Since you didn’t fix the typo, I am updating the offer on this pull request. I fixed the typo…
**However!** I changed the x position of a piece of text by 0.01.

***
## Description
I fixed the url-breaking bug on line 4 of README.md:
```md
It's an example on how to use the [PeasAPI](https://github.com/Peasplayer/PeasAP)
```
I replaced `/PeasAP` with `/PeasAPI` as seen here:
```md
It's an example on how to use the [PeasAPI](https://github.com/Peasplayer/PeasAPI)
```
As an exchange I changed a value in line 29 of Jester/JesterPlugin.cs that has no significant effects on the game, originally, the line looked like this:
```cs
Watermark.VersionTextOffset = new Vector3(0f, -0.4f, 0f);
```
I replaced `-0.4f` with `-0.41f` as seen here:
```cs
Watermark.VersionTextOffset = new Vector3(0f, -0.41f, 0f);
```
I simply changed a typo in exchange for a negligible change in numbers. Neither you nor I are impacted in any way from this pull request besides the removal of the typo.

***
## Counterargument
I now understand why you declined that pull request, it was a exchange of one typo for another. To you, this pull request might be almost as bad, I fix a typo but it would annoy detail-oriented people. Like, why wouldn’t I just fix the typo and nothing else?

***
## Rebuttal
I understand the counterargument but my services aren’t free and require some form of payment. *“Caveat Emptor”*, I told you exactly what I changed so you could fix it after the pull request. Not everyday someone gets the opportunity to exchange a typo for a less precise numerical value.

***
## Conclusion
Accept the pull request. No bug nor error is generated as a result. You have nothing to lose besides misaligned text by 1 pixel… To accept, click **Merge pull request**.

**Comment by Peasplayer** [comment]
Welcome to the contributors

**Review by Peasplayer — APPROVED** [review]

**Comment by KyleSmith0905** [comment]
Oh 🥵 my... 👨 I 🌊 can't 🤷‍♂️ believe 👀 you 👈 accepted ☺️👍 the merge... It means 😏 a lot 👑

**Comment by diceflip** [comment]
https://www.youtube.com/watch?v=Y9kMcHf5678

**Pull request merged**
